# TheoDB umbrella extension — PGXS build (SQL-only, no MODULES/.so).
# The AI surface is plpython3u + plpgsql, so this is a control+SQL extension (the pgvector model),
# NOT pgrx (M15 ADR D1). `make install` places theodb.control + sql/theodb--*.sql into the PG
# extension dir. The install script is generated by concatenating the modular bodies in load order.

EXTENSION = theodb
EXTVERSION = 1.0

# Upgrade scripts (theodb--X--Y.sql) ship as-is; the install script (theodb--1.0.sql) is generated.
DATA = $(wildcard sql/theodb--*--*.sql)
DATA_built = sql/$(EXTENSION)--$(EXTVERSION).sql

# Source bodies, concatenated in load order (50 before 70; 60 before 61) — see Dockerfile history.
PARTS = sql/30-theodb-embed.sql sql/40-theodb-hybrid.sql sql/50-theodb-ai.sql \
        sql/60-theodb-nl.sql sql/61-theodb-nl-config.sql sql/70-theodb-ml.sql

# PGXS is only needed for `make install` / regress (it requires postgresql-server-dev). The concat
# target below works WITHOUT it, so the install script can be built in a runtime image that dropped the
# dev package (M15 ADR D2 / EC-2). Include PGXS only when pg_config resolves it.
PG_CONFIG ?= pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs 2>/dev/null)
ifneq ($(PGXS),)
include $(PGXS)
endif

$(DATA_built): $(PARTS)
	@echo '-- TheoDB umbrella extension v$(EXTVERSION) — GENERATED (do not edit; edit sql/NN-*.sql)' > $@
	@echo '-- deps: vector, vectorscale, plpython3u (theodb.control requires; installed via CASCADE)' >> $@
	cat $(PARTS) >> $@

.PHONY: theodb-build dist
theodb-build: $(DATA_built)

dist: $(DATA_built)
	mkdir -p dist
	git archive --format zip --prefix=$(EXTENSION)-$(EXTVERSION)/ -o dist/$(EXTENSION)-$(EXTVERSION).zip HEAD
