# TheoDB umbrella extension — PGXS build (SQL-only, no MODULES/.so).
# The AI surface is plpython3u + plpgsql, so this is a control+SQL extension (the pgvector model),
# NOT pgrx (M15 ADR D1). `make install` places theodb.control + sql/theodb--*.sql into the PG
# extension dir. The install script is generated by concatenating the modular bodies in load order.

EXTENSION = theodb
EXTVERSION = 1.0

# Upgrade scripts (theodb--X--Y.sql) ship as-is; the install script (theodb--1.0.sql) is generated.
DATA = $(wildcard sql/theodb--*--*.sql)
DATA_built = sql/$(EXTENSION)--$(EXTVERSION).sql

# Source bodies, concatenated in load order. A ORDEM É O PREFIXO NUMÉRICO de dois dígitos — não uma lista
# mantida à mão. Antes esta lista existia aqui E, repetida, no Dockerfile; um corpo novo exigia lembrar dos
# dois lugares, e esquecer o Dockerfile embarcava uma imagem sem a superfície nova, em silêncio. As duas
# pontas passam a derivar do mesmo glob. Prefixo de DOIS dígitos é o contrato: `sql/100-*.sql` ordenaria
# antes de `30-` e quebraria a ordem de carga — use 90-99 ou renumere.
PARTS = $(sort $(wildcard sql/[0-9][0-9]-theodb-*.sql))

# PGXS is only needed for `make install` / regress (it requires postgresql-server-dev). The concat
# target below works WITHOUT it, so the install script can be built in a runtime image that dropped the
# dev package (M15 ADR D2 / EC-2). Include PGXS only when pg_config resolves it.
PG_CONFIG ?= pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs 2>/dev/null)
ifneq ($(PGXS),)
include $(PGXS)
endif

$(DATA_built): $(PARTS)
	@echo '-- TheoDB umbrella extension v$(EXTVERSION) — GENERATED (do not edit; edit sql/NN-*.sql)' > $@
	@echo '-- dep: theodb_rs (theodb.control requires; instalado via CASCADE) — ele provê o tipo `vector`' >> $@
	@echo '-- own-code, os AMs ANN e os schemas theodb/ai. NÃO há dep de pgvector/pgvectorscale (removidos' >> $@
	@echo '-- em M69/M70, ADR-0029) nem de plpython3u (removido em M19).' >> $@
	cat $(PARTS) >> $@

.PHONY: theodb-build dist
theodb-build: $(DATA_built)

dist: $(DATA_built)
	mkdir -p dist
	git archive --format zip --prefix=$(EXTENSION)-$(EXTVERSION)/ -o dist/$(EXTENSION)-$(EXTVERSION).zip HEAD
