-- TheoDB M7-S1 / M19 — Hybrid search (FTS + vector) fused by Reciprocal Rank Fusion (RRF).
-- Mirrors AlloyDB's ai.hybrid_search() capability with permissive PostgreSQL primitives:
--   FTS leg  = PostgreSQL native full-text search (to_tsvector/@@/ts_rank_cd, GIN index)
--   vector leg = pgvector similarity (<=> cosine), HNSW index
--   fusion   = RRF, score(d) = sum over legs of 1/(k + rank_leg(d))   [Cormack et al., SIGIR'09]
-- The RRF math is the public Cormack 2009 technique (k=60 empirical default), NOT borrowed from any
-- AGPL implementation (D3 — ParadeDB pg_search is AGPL and barred by D1; read for technique only).
--
-- M19 (ROADMAP-v2): `ai.hybrid_search_rrf` AND `ai.hybrid_search(jsonb)` are now implemented in Rust by the
-- `theodb_rs` extension (theodb_rs/src/hybrid.rs) — NOT here. The Rust function is the ENTRYPOINT and owns
-- orchestration; the RRF fusion itself stays ONE SQL string run via SPI (one fusion source of truth — D2).
-- This file keeps only the `ai` schema bootstrap; the function definitions moved out. Empty-leg handling,
-- the 'english' FTS pin, %I identifier-quoting, and the `score DESC, id ASC` tie-break are all preserved in
-- the Rust port (proven by benchmarks/tests/test_integration.py + test_hybrid_guard.py against the image).
-- Idempotent: safe to re-run / load from docker-entrypoint-initdb.d.

-- dep (vector) declared in theodb.control `requires` (M15) — not created here
