\echo Use "ALTER EXTENSION theodb_rs UPDATE TO '1.3.0'" to load this file. \quit

-- M137 — salto CONVERGENTE 1.2.0 → 1.3.0.
-- GERADO por scripts/gen-upgrade-script.py a partir do SQL de instalação do pgrx. NÃO editar à mão:
-- regenere. Editar um script já lançado nunca chega a quem já atualizou (lição do ParadeDB 0.24.1).
--
-- Convergente porque `1.2.0` rotula catálogos diferentes (a superfície foi 18→48→60→78 funções
-- com a versão congelada). Este script leva QUALQUER um deles ao estado 1.3.0, e é idempotente:
-- rodá-lo duas vezes não erra e não muda o schema.

-- (1) objetos que existiram em release anterior e não existem mais (medido, não presumido)
DROP FUNCTION IF EXISTS theodb_rs."_import_pinecone"(text, text, text, text, integer);
DROP FUNCTION IF EXISTS theodb."_import_pinecone"(text, text, text, text, integer);

-- (2) a superfície alvo, tornada idempotente

DO $theodb_up$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_type WHERE typname = 'vector' AND typnamespace = 'public'::regnamespace) THEN
/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/dtype.rs:387
-- bootstrap
CREATE TYPE vector;
  END IF;
END $theodb_up$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/am/columnar.rs:66

CREATE SCHEMA IF NOT EXISTS columnar;
CREATE TABLE IF NOT EXISTS columnar.stripe (
    relid            oid      NOT NULL,   -- pg_class OID of the columnar table (every scan filters on this)
    stripe_id        bigint   NOT NULL,   -- from reserve(StripeId); stable identity + tie-break order
    header_block     integer  NOT NULL,   -- block of the stripe's TCS1 header (navigates everything below)
    row_count        integer  NOT NULL,   -- rows in the stripe (planner stat)
    first_row_number bigint   NOT NULL,   -- reserve(RowNumber) base; deterministic scan order
    ncols            smallint NOT NULL,   -- cross-check vs live tupdesc.natts
    PRIMARY KEY (relid, stripe_id)
);
CREATE INDEX IF NOT EXISTS columnar_stripe_relid_rownum ON columnar.stripe (relid, first_row_number);

-- Reclaim orphaned stripe rows when a columnar table is dropped, so a later OID reuse can never inherit stale
-- stripes (the catalog has no FK to pg_class — the object is already gone by row-delete time).
CREATE OR REPLACE FUNCTION columnar._drop_cleanup() RETURNS event_trigger LANGUAGE plpgsql AS $fn$
BEGIN
    DELETE FROM columnar.stripe s
    USING pg_event_trigger_dropped_objects() d
    WHERE d.classid = 'pg_catalog.pg_class'::regclass AND s.relid = d.objid;
END;
$fn$;
DROP EVENT TRIGGER IF EXISTS columnar_drop_cleanup;
DO $theodb_up$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_event_trigger WHERE evtname = 'columnar_drop_cleanup') THEN
CREATE EVENT TRIGGER columnar_drop_cleanup ON sql_drop EXECUTE FUNCTION columnar._drop_cleanup();
  END IF;
END $theodb_up$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/am/arrow_cache.rs:30
-- requires:
--   theodb_columnar_catalog


CREATE SCHEMA IF NOT EXISTS columnar;
CREATE TABLE IF NOT EXISTS columnar.cache_state (
    relid      oid       PRIMARY KEY,
    generation bigint    NOT NULL DEFAULT 0,
    cols       text[]    NOT NULL
);
CREATE OR REPLACE FUNCTION columnar._invalidate() RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
    UPDATE columnar.cache_state SET generation = generation + 1 WHERE relid = TG_RELID;
    RETURN NULL;
END;
$fn$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/dtype.rs:391
CREATE SCHEMA IF NOT EXISTS theodb; CREATE SCHEMA IF NOT EXISTS ai;
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph.rs:27
-- requires:
--   theodb_schema_bootstrap


CREATE TABLE IF NOT EXISTS theodb.graph_csr (
    edge_rel   oid PRIMARY KEY,
    src_col    text NOT NULL,
    dst_col    text NOT NULL,
    nnodes     bigint NOT NULL,
    nedges     bigint NOT NULL,
    csr        bytea NOT NULL,
    built_at   timestamptz NOT NULL DEFAULT now()
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph.rs:616
-- requires:
--   theodb_graph_schema


CREATE OR REPLACE FUNCTION theodb.graph_on_drop() RETURNS event_trigger LANGUAGE plpgsql AS $fn$
DECLARE r record;
BEGIN
    FOR r IN SELECT objid FROM pg_event_trigger_dropped_objects() WHERE object_type = 'table' LOOP
        DELETE FROM theodb.graph_csr WHERE edge_rel = r.objid;
    END LOOP;
END $fn$;
DO $theodb_up$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_event_trigger WHERE evtname = 'theodb_graph_drop') THEN
CREATE EVENT TRIGGER theodb_graph_drop ON sql_drop EXECUTE FUNCTION theodb.graph_on_drop();
  END IF;
END $theodb_up$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/vectorizer.rs:23
-- requires:
--   theodb_schema_bootstrap


CREATE TABLE IF NOT EXISTS theodb.vectorizer (
    id             serial PRIMARY KEY,
    source_table   text NOT NULL,
    source_pk_col  text NOT NULL,
    content_col    text NOT NULL,
    target_table   text NOT NULL,
    target_col     text NOT NULL,
    model          text,
    dims           int,
    -- M66: opt-in declarative chunking. NULL chunk_strategy → the v1 in-place mode (1 doc → 1 vector,
    -- non-breaking). Non-NULL → 1 doc → N chunks → N rows in the `{target_table}_chunks` table.
    chunk_strategy text,
    chunk_size     int NOT NULL DEFAULT 512,
    chunk_overlap  int NOT NULL DEFAULT 64,
    created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS theodb.vectorizer_queue (
    job_id         bigserial PRIMARY KEY,
    vectorizer_id  int  NOT NULL REFERENCES theodb.vectorizer(id) ON DELETE CASCADE,
    source_pk      text NOT NULL,
    op             text NOT NULL DEFAULT 'upsert' CHECK (op IN ('upsert','delete')),
    state          text NOT NULL DEFAULT 'pending' CHECK (state IN ('pending','processing','failed')),
    attempts       int  NOT NULL DEFAULT 0,
    owner          text,
    lease_deadline timestamptz,
    last_error     text,
    enqueued_at    timestamptz NOT NULL DEFAULT now()
);

-- Partial: excludes `failed` dead-letter tombstones so the claim scan stays enxuto as they accumulate
-- (council-index-storage M-3). Covers both the `pending` and the `processing`-reclaim branches.
CREATE INDEX IF NOT EXISTS vectorizer_queue_claim_idx
    ON theodb.vectorizer_queue (state, enqueued_at)
    WHERE state IN ('pending', 'processing');

-- M104 producer backpressure via COALESCING: at most ONE pending job per (vectorizer_id, source_pk). A bulk
-- backfill / repeated UPDATE that re-enqueues the same row is de-duplicated (ON CONFLICT DO NOTHING on the
-- enqueue), so the pending queue depth is bounded by the DISTINCT pending work set — the single worker cannot be
-- flooded past the number of distinct rows that actually changed (the audit's producer-faster-than-consumer gap).
CREATE UNIQUE INDEX IF NOT EXISTS vectorizer_queue_pending_uniq
    ON theodb.vectorizer_queue (vectorizer_id, source_pk)
    WHERE state = 'pending';
/* </end connected objects> */

/* <begin connected objects> */
-- src/vectorizer.rs:77
-- requires:
--   theodb_vectorizer_schema


-- Generic enqueue trigger: TG_ARGV[0]=vectorizer_id, TG_ARGV[1]=source_pk_col. The PK is extracted as text
-- via to_jsonb(row)->>col (no dynamic EXECUTE needed). Enqueues 'delete' on DELETE, else 'upsert'.
CREATE OR REPLACE FUNCTION theodb._vectorizer_enqueue() RETURNS trigger LANGUAGE plpgsql AS $fn$
DECLARE
    vid   int  := TG_ARGV[0]::int;
    pkcol text := TG_ARGV[1];
BEGIN
    IF TG_OP = 'DELETE' THEN
        INSERT INTO theodb.vectorizer_queue (vectorizer_id, source_pk, op)
        VALUES (vid, to_jsonb(OLD) ->> pkcol, 'delete')
        -- coalesce: one pending job per (vectorizer,PK); last op wins (a delete after a pending upsert must
        -- supersede it — the net state is "deleted"). enqueued_at is preserved to keep FIFO order (a hot row
        -- re-touched forever cannot starve older work by resetting its position).
        ON CONFLICT (vectorizer_id, source_pk) WHERE state = 'pending' DO UPDATE SET op = EXCLUDED.op;
        RETURN OLD;
    END IF;
    INSERT INTO theodb.vectorizer_queue (vectorizer_id, source_pk, op)
    VALUES (vid, to_jsonb(NEW) ->> pkcol, 'upsert')
    ON CONFLICT (vectorizer_id, source_pk) WHERE state = 'pending' DO UPDATE SET op = EXCLUDED.op;
    RETURN NEW;
END;
$fn$;

-- Declarative registration: record the config + attach the enqueue trigger to the source table. Returns the
-- vectorizer id. Idempotent-ish: a second call on the same table creates a second vectorizer/trigger (by id)
-- — callers dedupe by not re-registering. The AFTER trigger name is namespaced by id so several can coexist.
CREATE OR REPLACE FUNCTION theodb.create_vectorizer(
    source_table   regclass,
    source_pk_col  text,
    content_col    text,
    target_table   regclass,
    target_col     text,
    model          text DEFAULT NULL,
    dims           int  DEFAULT NULL,
    chunk_strategy text DEFAULT NULL,
    chunk_size     int  DEFAULT 512,
    chunk_overlap  int  DEFAULT 64
) RETURNS int LANGUAGE plpgsql AS $fn$
DECLARE
    vid    int;
    tgname text;
BEGIN
    -- Validate chunking config at the boundary (fail-fast, Rule 8) — the chunker also validates, but the
    -- DDL should reject a bad config before any row is processed.
    IF chunk_strategy IS NOT NULL THEN
        IF chunk_strategy NOT IN ('fixed','sentence','recursive') THEN
            RAISE EXCEPTION 'theodb.create_vectorizer: unknown chunk_strategy % (valid: fixed, sentence, recursive)', chunk_strategy;
        END IF;
        IF chunk_size <= 0 OR chunk_overlap < 0 OR chunk_overlap >= chunk_size THEN
            RAISE EXCEPTION 'theodb.create_vectorizer: require chunk_size > 0 and 0 <= overlap < chunk_size (got size %, overlap %)', chunk_size, chunk_overlap;
        END IF;
    END IF;
    INSERT INTO theodb.vectorizer (source_table, source_pk_col, content_col, target_table, target_col, model, dims, chunk_strategy, chunk_size, chunk_overlap)
    VALUES (source_table::text, source_pk_col, content_col, target_table, target_col, model, dims, chunk_strategy, chunk_size, chunk_overlap)
    RETURNING id INTO vid;

    -- M66: when chunking is enabled, provision the sibling chunk table (1 doc → N chunks). Idempotent.
    IF chunk_strategy IS NOT NULL THEN
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %s_chunks (source_pk text NOT NULL, chunk_index int NOT NULL, '
            'chunk_text text NOT NULL, embedding vector%s, PRIMARY KEY (source_pk, chunk_index))',
            target_table::text, CASE WHEN dims IS NULL THEN '' ELSE '('||dims||')' END);
    END IF;

    tgname := format('theodb_vectorizer_%s', vid);
    EXECUTE format(
        'CREATE TRIGGER %I AFTER INSERT OR UPDATE OR DELETE ON %s '
        'FOR EACH ROW EXECUTE FUNCTION theodb._vectorizer_enqueue(%L, %L)',
        tgname, source_table::text, vid::text, source_pk_col);
    RETURN vid;
END;
$fn$;

COMMENT ON FUNCTION theodb.create_vectorizer(regclass, text, text, regclass, text, text, int, text, int, int) IS
  'Declaratively maintain an embedding column: attach an AFTER INSERT/UPDATE/DELETE trigger to source_table '
  'that enqueues jobs into theodb.vectorizer_queue; the background worker drains them (M54, ADR 0016). The '
  'trigger only enqueues (cheap, no HTTP) — model latency stays off the writer transaction.';

-- (M66) the v1 plpgsql `theodb.chunk_text` was removed here — superseded by the Rust `theodb.chunk`
-- (fixed/sentence/recursive + overlap, Unicode-safe; `theodb_rs::chunk`, wired in api.rs). One chunker (KISS).

REVOKE ALL ON FUNCTION theodb.create_vectorizer(regclass, text, text, regclass, text, text, int, text, int, int) FROM PUBLIC;

-- Runtime metric (wiring triad pillar c): a single-row counter of jobs the worker processed / failed. The
-- worker bumps it via theodb_rs._vectorizer_bump_stats. Queryable (not just a LOG line) via theodb.vectorizer_stats().
CREATE TABLE IF NOT EXISTS theodb.vectorizer_worker_stats (
    only_row  boolean PRIMARY KEY DEFAULT true CHECK (only_row),
    processed bigint  NOT NULL DEFAULT 0,
    failed    bigint  NOT NULL DEFAULT 0,
    last_run  timestamptz
);
INSERT INTO theodb.vectorizer_worker_stats (only_row) VALUES (true) ON CONFLICT DO NOTHING;

-- The queryable metric: worker throughput (processed/failed cumulative) + live queue depth by state.
CREATE OR REPLACE FUNCTION theodb.vectorizer_stats()
RETURNS TABLE(processed bigint, failed bigint, last_run timestamptz, pending bigint, processing bigint, failed_jobs bigint)
LANGUAGE sql STABLE AS $fn$
    SELECT s.processed, s.failed, s.last_run,
           (SELECT count(*) FROM theodb.vectorizer_queue WHERE state='pending'),
           (SELECT count(*) FROM theodb.vectorizer_queue WHERE state='processing'),
           (SELECT count(*) FROM theodb.vectorizer_queue WHERE state='failed')
    FROM theodb.vectorizer_worker_stats s
$fn$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/am/autotune.rs:87
-- requires:
--   theodb_schema_bootstrap


CREATE TABLE IF NOT EXISTS theodb._index_scan_stats (
    relid         oid  PRIMARY KEY,
    n_scans       bigint      NOT NULL DEFAULT 0,
    sum_pages_read bigint     NOT NULL DEFAULT 0,
    sum_candidates bigint     NOT NULL DEFAULT 0,
    sum_latency_us bigint     NOT NULL DEFAULT 0,
    last_ef       int,
    last_updated  timestamptz NOT NULL DEFAULT now()
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph_extract.rs:237
-- requires:
--   theodb_schema_bootstrap


CREATE TABLE IF NOT EXISTS theodb.graph_nodes (
    id             bigserial PRIMARY KEY,
    workspace_id   text NOT NULL,
    collection_id  text NOT NULL,
    name           text NOT NULL,
    normalized_name text NOT NULL,
    type           text NOT NULL DEFAULT 'entity',
    mention_count  int  NOT NULL DEFAULT 1,
    UNIQUE (workspace_id, collection_id, normalized_name)
);
CREATE TABLE IF NOT EXISTS theodb.graph_edges (
    id             bigserial PRIMARY KEY,
    workspace_id   text NOT NULL,
    collection_id  text NOT NULL,
    src_id         bigint NOT NULL,
    dst_id         bigint NOT NULL,
    weight         int  NOT NULL DEFAULT 1,
    description    text NOT NULL DEFAULT '',
    source_chunk_ids text[] NOT NULL DEFAULT '{}',
    UNIQUE (workspace_id, collection_id, src_id, dst_id)
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/parquet.rs:84
-- theodb_rs::parquet::olap
CREATE OR REPLACE  FUNCTION "olap"(
	"path" TEXT /* String */
) RETURNS TABLE (
	"category" TEXT,  /* String */
	"c" bigint,  /* i64 */
	"a" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'olap_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/parquet.rs:127
-- theodb_rs::parquet::read_parquet
CREATE OR REPLACE  FUNCTION "read_parquet"(
	"path" TEXT /* String */
) RETURNS SETOF jsonb /* pgrx :: JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'read_parquet_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bench_symqg.rs:47
-- theodb_rs::bench_symqg::symqg_spike_bench
CREATE OR REPLACE  FUNCTION "symqg_spike_bench"(
	"sift_dir" TEXT, /* & str */
	"n" bigint, /* i64 */
	"nq" bigint, /* i64 */
	"bits" INT /* i32 */
) RETURNS TEXT /* String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'symqg_spike_bench_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bench_symqg.rs:113
-- requires:
--   symqg_spike_bench

REVOKE ALL ON FUNCTION symqg_spike_bench(text, bigint, bigint, int) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/am/arrow_cache.rs:246
-- theodb_rs::am::arrow_cache::theodb_cache_refresh
CREATE OR REPLACE  FUNCTION "theodb_cache_refresh"(
	"table" oid /* pg_sys :: Oid */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_cache_refresh_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/am/columnar.rs:224
-- theodb_rs::am::columnar::theodb_columnar_tam_handler

    CREATE OR REPLACE FUNCTION theodb_columnar_tam_handler(internal) RETURNS table_am_handler
        LANGUAGE c AS 'MODULE_PATHNAME', 'theodb_columnar_tam_handler_wrapper';
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_am WHERE amname = 'theodb_columnar') THEN
            CREATE ACCESS METHOD theodb_columnar TYPE TABLE HANDLER theodb_columnar_tam_handler;
        END IF;
    END;
    $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/am/arrow_cache.rs:205
-- theodb_rs::am::arrow_cache::theodb_columnarize
CREATE OR REPLACE  FUNCTION "theodb_columnarize"(
	"table" oid, /* pg_sys :: Oid */
	"cols" TEXT[] /* Vec < String > */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_columnarize_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/am/datafusion_probe.rs:50
-- theodb_rs::am::datafusion_probe::theodb_df_probe
CREATE OR REPLACE  FUNCTION "theodb_df_probe"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_df_probe_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/am/mod.rs:64
-- theodb_rs::am::theodb_hnsw_amhandler

    CREATE OR REPLACE FUNCTION theodb_hnsw_amhandler(internal) RETURNS index_am_handler
        PARALLEL SAFE IMMUTABLE STRICT COST 0.0001 LANGUAGE c AS 'MODULE_PATHNAME', 'theodb_hnsw_amhandler_wrapper';
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_am WHERE amname = 'theodb_hnsw') THEN
            CREATE ACCESS METHOD theodb_hnsw TYPE INDEX HANDLER theodb_hnsw_amhandler;
        END IF;
    END;
    $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/am/mod.rs:47
-- theodb_rs::am::theodb_ivfflat_amhandler

    CREATE OR REPLACE FUNCTION theodb_ivfflat_amhandler(internal) RETURNS index_am_handler
        PARALLEL SAFE IMMUTABLE STRICT COST 0.0001 LANGUAGE c AS 'MODULE_PATHNAME', 'theodb_ivfflat_amhandler_wrapper';
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_am WHERE amname = 'theodb_ivfflat') THEN
            CREATE ACCESS METHOD theodb_ivfflat TYPE INDEX HANDLER theodb_ivfflat_amhandler;
        END IF;
    END;
    $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/am/mod.rs:315
-- theodb_rs::am::theodb_metric_cosine
CREATE OR REPLACE  FUNCTION "theodb_metric_cosine"() RETURNS INT /* i32 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_metric_cosine_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/am/mod.rs:310
-- theodb_rs::am::theodb_metric_ip
CREATE OR REPLACE  FUNCTION "theodb_metric_ip"() RETURNS INT /* i32 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_metric_ip_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/am/mod.rs:324
-- theodb_rs::am::theodb_smallint_array_overlap
CREATE OR REPLACE FUNCTION "theodb_smallint_array_overlap"(
	"left" smallint[], /* Array < i16 > */
	"right" smallint[] /* Array < i16 > */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_smallint_array_overlap_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/am/mod.rs:81
-- theodb_rs::am::theodb_symqg_amhandler

    CREATE OR REPLACE FUNCTION theodb_symqg_amhandler(internal) RETURNS index_am_handler
        PARALLEL SAFE IMMUTABLE STRICT COST 0.0001 LANGUAGE c AS 'MODULE_PATHNAME', 'theodb_symqg_amhandler_wrapper';
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_am WHERE amname = 'theodb_symqg') THEN
            CREATE ACCESS METHOD theodb_symqg TYPE INDEX HANDLER theodb_symqg_amhandler;
        END IF;
    END;
    $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/dtype.rs:269
-- theodb_rs::dtype::theodb_vector_coerce
CREATE OR REPLACE  FUNCTION "theodb_vector_coerce"(
	"v" vector, /* Vector */
	"typmod" INT, /* i32 */
	"_explicit" bool /* bool */
) RETURNS vector /* Vector */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_vector_coerce_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/dtype.rs:342
-- theodb_rs::dtype::theodb_vector_cosine_distance
CREATE OR REPLACE  FUNCTION "theodb_vector_cosine_distance"(
	"a" vector, /* Vector */
	"b" vector /* Vector */
) RETURNS double precision /* f64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_vector_cosine_distance_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/dtype.rs:375
-- theodb_rs::dtype::theodb_vector_from_float8_array
CREATE OR REPLACE  FUNCTION "theodb_vector_from_float8_array"(
	"arr" double precision[] /* Vec < f64 > */
) RETURNS vector /* Vector */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_vector_from_float8_array_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/dtype.rs:357
-- theodb_rs::dtype::theodb_vector_from_real_array
CREATE OR REPLACE  FUNCTION "theodb_vector_from_real_array"(
	"arr" real[] /* Vec < f32 > */
) RETURNS vector /* Vector */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_vector_from_real_array_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/dtype.rs:230
-- theodb_rs::dtype::theodb_vector_in
CREATE OR REPLACE  FUNCTION "theodb_vector_in"(
	"input" cstring, /* & CStr */
	"_oid" oid, /* Oid */
	"typmod" INT /* i32 */
) RETURNS vector /* Vector */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_vector_in_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/dtype.rs:330
-- theodb_rs::dtype::theodb_vector_l2_distance
CREATE OR REPLACE  FUNCTION "theodb_vector_l2_distance"(
	"a" vector, /* Vector */
	"b" vector /* Vector */
) RETURNS double precision /* f64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_vector_l2_distance_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/dtype.rs:336
-- theodb_rs::dtype::theodb_vector_neg_inner_product
CREATE OR REPLACE  FUNCTION "theodb_vector_neg_inner_product"(
	"a" vector, /* Vector */
	"b" vector /* Vector */
) RETURNS double precision /* f64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_vector_neg_inner_product_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/dtype.rs:243
-- theodb_rs::dtype::theodb_vector_out
CREATE OR REPLACE  FUNCTION "theodb_vector_out"(
	"v" vector /* Vector */
) RETURNS cstring /* CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_vector_out_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/dtype.rs:280
-- theodb_rs::dtype::theodb_vector_recv
CREATE OR REPLACE  FUNCTION "theodb_vector_recv"(
	"internal" internal, /* pgrx :: datum :: Internal */
	"_oid" oid, /* Oid */
	"typmod" INT /* i32 */
) RETURNS vector /* Vector */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_vector_recv_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/dtype.rs:314
-- theodb_rs::dtype::theodb_vector_send
CREATE OR REPLACE  FUNCTION "theodb_vector_send"(
	"v" vector /* Vector */
) RETURNS bytea /* Vec < u8 > */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_vector_send_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/dtype.rs:370
-- theodb_rs::dtype::theodb_vector_to_real_array
CREATE OR REPLACE  FUNCTION "theodb_vector_to_real_array"(
	"v" vector /* Vector */
) RETURNS real[] /* Vec < f32 > */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_vector_to_real_array_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/dtype.rs:248
-- theodb_rs::dtype::theodb_vector_typmod_in
CREATE OR REPLACE  FUNCTION "theodb_vector_typmod_in"(
	"list" cstring[] /* pgrx :: Array < & CStr > */
) RETURNS INT /* i32 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_vector_typmod_in_wrapper';
DO $theodb_up$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_type WHERE typname = 'vector' AND typnamespace = 'public'::regnamespace AND typisdefined) THEN
/* </end connected objects> */

/* <begin connected objects> */
-- src/dtype.rs:396
-- requires:
--   vector_shell
--   theodb_vector_in
--   theodb_vector_out
--   theodb_vector_recv
--   theodb_vector_send
--   theodb_vector_typmod_in
--   theodb_vector_coerce
--   theodb_vector_l2_distance
--   theodb_vector_neg_inner_product
--   theodb_vector_cosine_distance
--   theodb_vector_from_real_array
--   theodb_vector_to_real_array
--   theodb_vector_from_float8_array


CREATE TYPE vector (
    INPUT     = theodb_vector_in,
    OUTPUT    = theodb_vector_out,
    RECEIVE   = theodb_vector_recv,
    SEND      = theodb_vector_send,
    TYPMOD_IN = theodb_vector_typmod_in,
    STORAGE   = external,
    INTERNALLENGTH = variable
);
  END IF;
END $theodb_up$;
DO $theodb_up$ BEGIN

CREATE CAST (vector AS vector)
    WITH FUNCTION theodb_vector_coerce(vector, integer, boolean) AS IMPLICIT;
EXCEPTION WHEN duplicate_object OR duplicate_function THEN NULL;
END $theodb_up$;
DO $theodb_up$ BEGIN

CREATE OPERATOR <-> (
    LEFTARG = vector, RIGHTARG = vector,
    PROCEDURE = theodb_vector_l2_distance, COMMUTATOR = '<->'
);
EXCEPTION WHEN duplicate_object OR duplicate_function THEN NULL;
END $theodb_up$;
DO $theodb_up$ BEGIN
CREATE OPERATOR <#> (
    LEFTARG = vector, RIGHTARG = vector,
    PROCEDURE = theodb_vector_neg_inner_product, COMMUTATOR = '<#>'
);
EXCEPTION WHEN duplicate_object OR duplicate_function THEN NULL;
END $theodb_up$;
DO $theodb_up$ BEGIN
CREATE OPERATOR <=> (
    LEFTARG = vector, RIGHTARG = vector,
    PROCEDURE = theodb_vector_cosine_distance, COMMUTATOR = '<=>'
);
EXCEPTION WHEN duplicate_object OR duplicate_function THEN NULL;
END $theodb_up$;
DO $theodb_up$ BEGIN

CREATE CAST (real[] AS vector)  WITH FUNCTION theodb_vector_from_real_array(real[]);
EXCEPTION WHEN duplicate_object OR duplicate_function THEN NULL;
END $theodb_up$;
DO $theodb_up$ BEGIN
CREATE CAST (vector AS real[])  WITH FUNCTION theodb_vector_to_real_array(vector);
EXCEPTION WHEN duplicate_object OR duplicate_function THEN NULL;
END $theodb_up$;
DO $theodb_up$ BEGIN
CREATE CAST (double precision[] AS vector) WITH FUNCTION theodb_vector_from_float8_array(double precision[]);
EXCEPTION WHEN duplicate_object OR duplicate_function THEN NULL;
END $theodb_up$;
DO $theodb_up$ BEGIN
/* </end connected objects> */

/* <begin connected objects> */
-- src/am/mod.rs:358
-- requires:
--   theodb_hnsw_amhandler
--   vector_type


    CREATE OPERATOR CLASS theodb_hnsw_l2_ops DEFAULT FOR TYPE vector USING theodb_hnsw AS
        OPERATOR 1 <-> (vector, vector) FOR ORDER BY float_ops;
EXCEPTION WHEN duplicate_object OR duplicate_function THEN NULL;
END $theodb_up$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph_rag.rs:14
-- requires:
--   theodb_graph_extract_schema
--   vector_type


ALTER TABLE theodb.graph_nodes ADD COLUMN IF NOT EXISTS embedding public.vector;
DO $theodb_up$ BEGIN
/* </end connected objects> */

/* <begin connected objects> */
-- src/am/mod.rs:348
-- requires:
--   theodb_ivfflat_amhandler
--   vector_type


    CREATE OPERATOR CLASS theodb_ivfflat_l2_ops DEFAULT FOR TYPE vector USING theodb_ivfflat AS
        OPERATOR 1 <-> (vector, vector) FOR ORDER BY float_ops;
EXCEPTION WHEN duplicate_object OR duplicate_function THEN NULL;
END $theodb_up$;
DO $theodb_up$ BEGIN
/* </end connected objects> */

/* <begin connected objects> */
-- src/am/mod.rs:381
-- requires:
--   vector_type
--   theodb_ivfflat_amhandler
--   theodb_hnsw_amhandler
--   theodb_ivfflat_opclasses
--   theodb_hnsw_opclasses
--   theodb_metric_cosine
--   theodb_metric_ip


    CREATE OPERATOR CLASS theodb_ivfflat_cosine_ops FOR TYPE vector USING theodb_ivfflat AS
        OPERATOR 1 <=> (vector, vector) FOR ORDER BY float_ops,
        FUNCTION 1 theodb_metric_cosine();
EXCEPTION WHEN duplicate_object OR duplicate_function THEN NULL;
END $theodb_up$;
DO $theodb_up$ BEGIN
    CREATE OPERATOR CLASS theodb_ivfflat_ip_ops FOR TYPE vector USING theodb_ivfflat AS
        OPERATOR 1 <#> (vector, vector) FOR ORDER BY float_ops,
        FUNCTION 1 theodb_metric_ip();
EXCEPTION WHEN duplicate_object OR duplicate_function THEN NULL;
END $theodb_up$;
DO $theodb_up$ BEGIN
    CREATE OPERATOR CLASS theodb_hnsw_cosine_ops FOR TYPE vector USING theodb_hnsw AS
        OPERATOR 1 <=> (vector, vector) FOR ORDER BY float_ops,
        FUNCTION 1 theodb_metric_cosine();
EXCEPTION WHEN duplicate_object OR duplicate_function THEN NULL;
END $theodb_up$;
DO $theodb_up$ BEGIN
    CREATE OPERATOR CLASS theodb_hnsw_ip_ops FOR TYPE vector USING theodb_hnsw AS
        OPERATOR 1 <#> (vector, vector) FOR ORDER BY float_ops,
        FUNCTION 1 theodb_metric_ip();
EXCEPTION WHEN duplicate_object OR duplicate_function THEN NULL;
END $theodb_up$;
DO $theodb_up$ BEGIN
/* </end connected objects> */

/* <begin connected objects> */
-- src/am/mod.rs:413
-- requires:
--   theodb_ivfflat_amhandler
--   theodb_smallint_array_overlap
--   theodb_ivfflat_opclasses


    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_operator
            WHERE oprname = '&&' AND oprleft = 'smallint[]'::regtype AND oprright = 'smallint[]'::regtype
        ) THEN
            CREATE OPERATOR && (
                LEFTARG = smallint[], RIGHTARG = smallint[],
                PROCEDURE = theodb_smallint_array_overlap,
                COMMUTATOR = &&, RESTRICT = contsel, JOIN = contjoinsel
            );
        END IF;
    END;
    $$;
EXCEPTION WHEN duplicate_object OR duplicate_function THEN NULL;
END $theodb_up$;
DO $theodb_up$ BEGIN
    CREATE OPERATOR CLASS theodb_ivfflat_label_ops DEFAULT FOR TYPE smallint[] USING theodb_ivfflat AS
        OPERATOR 1 && (smallint[], smallint[]);
EXCEPTION WHEN duplicate_object OR duplicate_function THEN NULL;
END $theodb_up$;
DO $theodb_up$ BEGIN
/* </end connected objects> */

/* <begin connected objects> */
-- src/am/mod.rs:369
-- requires:
--   theodb_symqg_amhandler
--   vector_type


    CREATE OPERATOR CLASS theodb_symqg_l2_ops DEFAULT FOR TYPE vector USING theodb_symqg AS
        OPERATOR 1 <-> (vector, vector) FOR ORDER BY float_ops;
EXCEPTION WHEN duplicate_object OR duplicate_function THEN NULL;
END $theodb_up$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/parquet.rs:174
-- theodb_rs::parquet::write_parquet
CREATE OR REPLACE  FUNCTION "write_parquet"(
	"rel" TEXT, /* String */
	"path" TEXT /* String */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'write_parquet_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/parquet.rs:447
-- requires:
--   write_parquet
--   read_parquet
--   olap


REVOKE ALL ON FUNCTION public.write_parquet(text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.read_parquet(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.olap(text) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/vindex.rs:174
CREATE SCHEMA IF NOT EXISTS theodb_rs; /* theodb_rs::vindex::theodb_rs */
/* </end connected objects> */

/* <begin connected objects> */
-- src/vindex.rs:223
-- theodb_rs::vindex::theodb_rs::_vindex_knn_columnar
CREATE OR REPLACE  FUNCTION theodb_rs."_vindex_knn_columnar"(
	"idx" oid, /* pg_sys :: Oid */
	"query" real[], /* Vec < Option < f32 > > */
	"k" INT, /* i32 */
	"_probes" INT, /* i32 */
	"label" INT /* i32 */
) RETURNS TABLE (
	"tid" bigint,  /* i64 */
	"dist" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_vindex_knn_columnar_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/vindex.rs:212
-- theodb_rs::vindex::theodb_rs::_vindex_decode_bytes
CREATE OR REPLACE  FUNCTION theodb_rs."_vindex_decode_bytes"(
	"idx" oid, /* pg_sys :: Oid */
	"cols" TEXT[] /* pgrx :: Array < '_, & str > */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_vindex_decode_bytes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/vindex.rs:195
-- theodb_rs::vindex::theodb_rs::_vindex_assign
CREATE OR REPLACE  FUNCTION theodb_rs."_vindex_assign"(
	"vecs" bytea[], /* pgrx :: Array < '_, & [u8] > */
	"nlist" INT /* i32 */
) RETURNS INT[] /* Vec < i32 > */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_vindex_assign_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/vindex.rs:180
-- theodb_rs::vindex::theodb_rs::_f32vec_to_bytea
CREATE OR REPLACE  FUNCTION theodb_rs."_f32vec_to_bytea"(
	"v" real[] /* Vec < Option < f32 > > */
) RETURNS bytea /* Vec < u8 > */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_f32vec_to_bytea_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/vindex.rs:327
-- requires:
--   _f32vec_to_bytea
--   _vindex_assign
--   _vindex_knn_columnar
--   _vindex_decode_bytes
--   theodb_schema_bootstrap


CREATE OR REPLACE FUNCTION theodb.f32vec_to_bytea(v float4[]) RETURNS bytea LANGUAGE sql IMMUTABLE
AS $$ SELECT theodb_rs._f32vec_to_bytea(v) $$;

CREATE OR REPLACE FUNCTION theodb.vindex_assign(vecs bytea[], nlist int) RETURNS int[] LANGUAGE sql VOLATILE
AS $$ SELECT theodb_rs._vindex_assign(vecs, nlist) $$;

CREATE OR REPLACE FUNCTION theodb.vindex_knn_columnar(idx regclass, query float4[], k int, probes int, label int)
RETURNS TABLE(tid bigint, dist float8) LANGUAGE sql VOLATILE
AS $$ SELECT * FROM theodb_rs._vindex_knn_columnar(idx::oid, query, k, probes, label) $$;

CREATE OR REPLACE FUNCTION theodb.vindex_decode_bytes(idx regclass, cols text[]) RETURNS bigint LANGUAGE sql VOLATILE
AS $$ SELECT theodb_rs._vindex_decode_bytes(idx::oid, cols) $$;

COMMENT ON FUNCTION theodb.vindex_knn_columnar(regclass, float4[], int, int, int) IS
  'M103 — co-resident filtered vector top-k over a theodb_columnar index: reads ONLY the tid/part_id/label/vec '
  'columns (column pruning), scalar prefilter + exact rerank, byte-identical to the exact filtered search. The '
  'probes argument is RESERVED — the columnar path currently runs full-probe (the byte-identity GATE); reduced-'
  'probe over columnar-stored centroids is a documented follow-up.';

REVOKE ALL ON FUNCTION theodb.vindex_knn_columnar(regclass, float4[], int, int, int) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb.vindex_assign(bytea[], int) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb.vindex_decode_bytes(regclass, text[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._vindex_knn_columnar(oid, float4[], int, int, int) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._vindex_assign(bytea[], int) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._vindex_decode_bytes(oid, text[]) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/ai_op.rs:74
CREATE SCHEMA IF NOT EXISTS theodb_rs; /* theodb_rs::ai_op::theodb_rs */
/* </end connected objects> */

/* <begin connected objects> */
-- src/ai_op.rs:96
-- theodb_rs::ai_op::theodb_rs::_ai_if_costly
CREATE OR REPLACE  FUNCTION theodb_rs."_ai_if_costly"(
	"condition" TEXT, /* & str */
	"val" TEXT, /* & str */
	"model" TEXT /* Option < & str > */
) RETURNS bool /* bool */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_ai_if_costly_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/ai_op.rs:109
-- theodb_rs::ai_op::theodb_rs::_ai_call_reset
CREATE OR REPLACE  FUNCTION theodb_rs."_ai_call_reset"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_ai_call_reset_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/ai_op.rs:103
-- theodb_rs::ai_op::theodb_rs::_ai_call_count
CREATE OR REPLACE  FUNCTION theodb_rs."_ai_call_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_ai_call_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/ai_op.rs:80
-- theodb_rs::ai_op::theodb_rs::_ai_if_batch
CREATE OR REPLACE  FUNCTION theodb_rs."_ai_if_batch"(
	"condition" TEXT, /* & str */
	"vals" TEXT[], /* :: std :: option :: Option < Vec < Option < String > > > */
	"model" TEXT /* Option < & str > */
) RETURNS bool[] /* Vec < Option < bool > > */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_ai_if_batch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph_extract.rs:265
CREATE SCHEMA IF NOT EXISTS theodb_rs; /* theodb_rs::graph_extract::theodb_rs */
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph_extract.rs:272
-- theodb_rs::graph_extract::theodb_rs::_extract_entities
CREATE OR REPLACE  FUNCTION theodb_rs."_extract_entities"(
	"text" TEXT, /* & str */
	"use_llm" bool, /* bool */
	"model" TEXT /* Option < & str > */
) RETURNS TABLE (
	"name" TEXT,  /* String */
	"normalized_name" TEXT,  /* String */
	"entity_type" TEXT,  /* String */
	"mention_count" INT  /* i32 */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_extract_entities_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph_extract.rs:312
-- theodb_rs::graph_extract::theodb_rs::_graph_upsert
CREATE OR REPLACE  FUNCTION theodb_rs."_graph_upsert"(
	"workspace_id" TEXT, /* & str */
	"collection_id" TEXT, /* & str */
	"source_chunk_id" TEXT, /* & str */
	"text" TEXT, /* & str */
	"use_llm" bool /* bool */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_graph_upsert_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph_extract.rs:291
-- theodb_rs::graph_extract::theodb_rs::_extract_graph
CREATE OR REPLACE  FUNCTION theodb_rs."_extract_graph"(
	"text" TEXT, /* & str */
	"use_llm" bool, /* bool */
	"model" TEXT /* Option < & str > */
) RETURNS TABLE (
	"src_normalized" TEXT,  /* String */
	"dst_normalized" TEXT,  /* String */
	"weight" INT,  /* i32 */
	"description" TEXT  /* String */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_extract_graph_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph_extract.rs:364
-- requires:
--   _extract_entities
--   _extract_graph
--   _graph_upsert
--   theodb_graph_extract_schema


CREATE OR REPLACE FUNCTION ai.extract_entities(text text, use_llm boolean DEFAULT false, model text DEFAULT NULL)
  RETURNS TABLE(name text, normalized_name text, entity_type text, mention_count int)
  LANGUAGE sql VOLATILE AS $fn$ SELECT * FROM theodb_rs._extract_entities($1,$2,$3) $fn$;
CREATE OR REPLACE FUNCTION ai.extract_graph(text text, use_llm boolean DEFAULT false, model text DEFAULT NULL)
  RETURNS TABLE(src_normalized text, dst_normalized text, weight int, description text)
  LANGUAGE sql VOLATILE AS $fn$ SELECT * FROM theodb_rs._extract_graph($1,$2,$3) $fn$;
CREATE OR REPLACE FUNCTION theodb.graph_upsert(workspace_id text, collection_id text, source_chunk_id text, text text, use_llm boolean DEFAULT false)
  RETURNS bigint LANGUAGE sql VOLATILE AS $fn$ SELECT theodb_rs._graph_upsert($1,$2,$3,$4,$5) $fn$;
REVOKE ALL ON FUNCTION ai.extract_entities(text,boolean,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION ai.extract_graph(text,boolean,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb.graph_upsert(text,text,text,text,boolean) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph_rag.rs:22
CREATE SCHEMA IF NOT EXISTS theodb_rs; /* theodb_rs::graph_rag::theodb_rs */
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph_rag.rs:28
-- theodb_rs::graph_rag::theodb_rs::_graph_embed_nodes
CREATE OR REPLACE  FUNCTION theodb_rs."_graph_embed_nodes"(
	"workspace_id" TEXT, /* & str */
	"collection_id" TEXT, /* & str */
	"model" TEXT /* Option < & str > */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_graph_embed_nodes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph_rag.rs:69
-- requires:
--   _graph_embed_nodes
--   theodb_graph_node_embedding
--   theodb_graph_extract_schema
--   vector_type


CREATE OR REPLACE FUNCTION theodb.graph_embed_nodes(workspace_id text, collection_id text, model text DEFAULT NULL)
  RETURNS bigint LANGUAGE sql VOLATILE AS $fn$ SELECT theodb_rs._graph_embed_nodes($1,$2,$3) $fn$;

CREATE OR REPLACE FUNCTION theodb.graph_rag_search(query_embedding public.vector, workspace_id text, collection_id text,
                                        k_entry int DEFAULT 5, max_hops int DEFAULT 2)
  RETURNS TABLE(chunk_id text, score float8) LANGUAGE sql STABLE AS $fn$
  WITH entry AS (
    SELECT id FROM theodb.graph_nodes
    WHERE workspace_id = $2 AND collection_id = $3 AND embedding IS NOT NULL
    ORDER BY embedding <=> $1
    LIMIT $4
  ),
  reached AS (
    SELECT t.node_id FROM theodb.graph_expand('theodb.graph_edges',
      (SELECT array_agg(id) FROM entry), $5) AS t(node_id)
  ),
  chunks AS (
    SELECT unnest(e.source_chunk_ids) AS chunk_id, e.weight
    FROM theodb.graph_edges e
    WHERE e.workspace_id = $2 AND e.collection_id = $3
      AND (e.src_id IN (SELECT node_id FROM reached) OR e.dst_id IN (SELECT node_id FROM reached))
  )
  SELECT chunk_id, sum(weight)::float8 AS score
  FROM chunks GROUP BY chunk_id ORDER BY score DESC, chunk_id
  $fn$;

REVOKE ALL ON FUNCTION theodb.graph_embed_nodes(text,text,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb.graph_rag_search(public.vector,text,text,int,int) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/vectorizer.rs:189
CREATE SCHEMA IF NOT EXISTS theodb_rs; /* theodb_rs::vectorizer::theodb_rs */
/* </end connected objects> */

/* <begin connected objects> */
-- src/vectorizer.rs:276
-- theodb_rs::vectorizer::theodb_rs::_vectorizer_mark_failed
CREATE OR REPLACE  FUNCTION theodb_rs."_vectorizer_mark_failed"(
	"job_id" bigint, /* i64 */
	"owner" TEXT, /* & str */
	"err" TEXT, /* & str */
	"max_attempts" INT /* i32 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_vectorizer_mark_failed_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/vectorizer.rs:498
-- theodb_rs::vectorizer::theodb_rs::_vectorizer_process_upsert_batch
CREATE OR REPLACE  FUNCTION theodb_rs."_vectorizer_process_upsert_batch"(
	"vectorizer_id" INT, /* i32 */
	"job_ids" bigint[], /* Vec < i64 > */
	"source_pks" TEXT[], /* Vec < String > */
	"owner" TEXT /* & str */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_vectorizer_process_upsert_batch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/vectorizer.rs:254
-- theodb_rs::vectorizer::theodb_rs::_vectorizer_mark_done
CREATE OR REPLACE  FUNCTION theodb_rs."_vectorizer_mark_done"(
	"job_id" bigint, /* i64 */
	"owner" TEXT /* & str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_vectorizer_mark_done_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/vectorizer.rs:654
-- theodb_rs::vectorizer::theodb_rs::_vectorizer_purge_dead_letters
CREATE OR REPLACE  FUNCTION theodb_rs."_vectorizer_purge_dead_letters"(
	"keep" INT /* i32 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_vectorizer_purge_dead_letters_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/vectorizer.rs:200
-- theodb_rs::vectorizer::theodb_rs::_vectorizer_claim_batch
CREATE OR REPLACE  FUNCTION theodb_rs."_vectorizer_claim_batch"(
	"owner" TEXT, /* & str */
	"batch" INT, /* i32 */
	"lease_secs" INT, /* i32 */
	"max_attempts" INT /* i32 */
) RETURNS TABLE (
	"job_id" bigint,  /* i64 */
	"vectorizer_id" INT,  /* i32 */
	"source_pk" TEXT,  /* String */
	"op" TEXT,  /* String */
	"attempts" INT  /* i32 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_vectorizer_claim_batch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/vectorizer.rs:463
-- theodb_rs::vectorizer::theodb_rs::_vectorizer_process_delete
CREATE OR REPLACE  FUNCTION theodb_rs."_vectorizer_process_delete"(
	"vectorizer_id" INT, /* i32 */
	"source_pk" TEXT /* & str */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_vectorizer_process_delete_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/vectorizer.rs:631
-- theodb_rs::vectorizer::theodb_rs::_vectorizer_reap_orphans
CREATE OR REPLACE  FUNCTION theodb_rs."_vectorizer_reap_orphans"(
	"max_attempts" INT /* i32 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_vectorizer_reap_orphans_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/vectorizer.rs:617
-- theodb_rs::vectorizer::theodb_rs::_vectorizer_bump_stats
CREATE OR REPLACE  FUNCTION theodb_rs."_vectorizer_bump_stats"(
	"processed" bigint, /* i64 */
	"failed" bigint /* i64 */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_vectorizer_bump_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/vectorizer.rs:431
-- theodb_rs::vectorizer::theodb_rs::_vectorizer_process_upsert
CREATE OR REPLACE  FUNCTION theodb_rs."_vectorizer_process_upsert"(
	"vectorizer_id" INT, /* i32 */
	"source_pk" TEXT /* & str */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_vectorizer_process_upsert_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/vectorizer.rs:312
-- theodb_rs::vectorizer::theodb_rs::_vectorizer_renew_lease
CREATE OR REPLACE  FUNCTION theodb_rs."_vectorizer_renew_lease"(
	"job_ids" bigint[], /* Vec < i64 > */
	"owner" TEXT, /* & str */
	"lease_secs" INT /* i32 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_vectorizer_renew_lease_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/vectorizer.rs:1114
-- requires:
--   _vectorizer_claim_batch
--   _vectorizer_mark_done
--   _vectorizer_mark_failed
--   _vectorizer_renew_lease
--   _vectorizer_process_upsert
--   _vectorizer_process_delete
--   _vectorizer_process_upsert_batch
--   _vectorizer_bump_stats
--   _vectorizer_reap_orphans
--   _vectorizer_purge_dead_letters


DO $$
DECLARE r record;
BEGIN
    FOR r IN SELECT p.oid::regprocedure AS sig
             FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
             WHERE n.nspname = 'theodb_rs' AND p.proname ~ '^_vectorizer_'
    LOOP
        EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC', r.sig);
    END LOOP;
END $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph.rs:347
CREATE SCHEMA IF NOT EXISTS theodb_rs; /* theodb_rs::graph::theodb_rs */
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph.rs:430
-- theodb_rs::graph::theodb_rs::graph_expand
CREATE OR REPLACE  FUNCTION theodb_rs."graph_expand"(
	"edge_rel" TEXT, /* & str */
	"seeds" bigint[], /* Vec < Option < i64 > > */
	"max_hops" INT /* i32 */
) RETURNS SETOF bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'graph_expand_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph.rs:454
-- theodb_rs::graph::theodb_rs::graph_ppr
CREATE OR REPLACE  FUNCTION theodb_rs."graph_ppr"(
	"edge_rel" TEXT, /* & str */
	"seeds" bigint[], /* Vec < Option < i64 > > */
	"damping" double precision, /* f64 */
	"iters" INT /* i32 */
) RETURNS TABLE (
	"node" bigint,  /* i64 */
	"score" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'graph_ppr_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph.rs:499
-- theodb_rs::graph::theodb_rs::graph_expand_multi_card
CREATE OR REPLACE  FUNCTION theodb_rs."graph_expand_multi_card"(
	"edge_rel" TEXT, /* & str */
	"set_ids" INT[], /* Vec < Option < i32 > > */
	"seeds" bigint[], /* Vec < Option < i64 > > */
	"max_hops" INT /* i32 */
) RETURNS TABLE (
	"set_id" INT,  /* i32 */
	"card" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'graph_expand_multi_card_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph.rs:478
-- theodb_rs::graph::theodb_rs::graph_expand_multi
CREATE OR REPLACE  FUNCTION theodb_rs."graph_expand_multi"(
	"edge_rel" TEXT, /* & str */
	"set_ids" INT[], /* Vec < Option < i32 > > */
	"seeds" bigint[], /* Vec < Option < i64 > > */
	"max_hops" INT /* i32 */
) RETURNS TABLE (
	"set_id" INT,  /* i32 */
	"node" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'graph_expand_multi_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph.rs:373
-- theodb_rs::graph::theodb_rs::graph_refold
CREATE OR REPLACE  FUNCTION theodb_rs."graph_refold"(
	"edge_rel" TEXT /* & str */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'graph_refold_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph.rs:444
-- theodb_rs::graph::theodb_rs::graph_expand_card
CREATE OR REPLACE  FUNCTION theodb_rs."graph_expand_card"(
	"edge_rel" TEXT, /* & str */
	"seeds" bigint[], /* Vec < Option < i64 > > */
	"max_hops" INT /* i32 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'graph_expand_card_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph.rs:355
-- theodb_rs::graph::theodb_rs::graph_build
CREATE OR REPLACE  FUNCTION theodb_rs."graph_build"(
	"edge_rel" TEXT, /* & str */
	"src_col" TEXT, /* & str */
	"dst_col" TEXT /* & str */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'graph_build_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph.rs:573
-- requires:
--   graph_build
--   graph_refold
--   graph_expand
--   graph_expand_card
--   graph_expand_multi
--   graph_expand_multi_card
--   graph_ppr
--   theodb_graph_schema


CREATE OR REPLACE FUNCTION theodb.graph_build(edge_rel text, src_col text, dst_col text) RETURNS bigint
  LANGUAGE sql VOLATILE AS $fn$ SELECT theodb_rs.graph_build($1,$2,$3) $fn$;
CREATE OR REPLACE FUNCTION theodb.graph_refold(edge_rel text) RETURNS bigint
  LANGUAGE sql VOLATILE AS $fn$ SELECT theodb_rs.graph_refold($1) $fn$;
CREATE OR REPLACE FUNCTION theodb.graph_expand(edge_rel text, seeds bigint[], max_hops int) RETURNS SETOF bigint
  LANGUAGE sql VOLATILE AS $fn$ SELECT theodb_rs.graph_expand($1,$2,$3) $fn$;
CREATE OR REPLACE FUNCTION theodb.graph_expand_card(edge_rel text, seeds bigint[], max_hops int) RETURNS bigint
  LANGUAGE sql VOLATILE AS $fn$ SELECT theodb_rs.graph_expand_card($1,$2,$3) $fn$;
CREATE OR REPLACE FUNCTION theodb.graph_expand_multi(edge_rel text, set_ids int[], seeds bigint[], max_hops int)
  RETURNS TABLE(set_id int, node bigint)
  LANGUAGE sql VOLATILE AS $fn$ SELECT * FROM theodb_rs.graph_expand_multi($1,$2,$3,$4) $fn$;
CREATE OR REPLACE FUNCTION theodb.graph_expand_multi_card(edge_rel text, set_ids int[], seeds bigint[], max_hops int)
  RETURNS TABLE(set_id int, card bigint)
  LANGUAGE sql VOLATILE AS $fn$ SELECT * FROM theodb_rs.graph_expand_multi_card($1,$2,$3,$4) $fn$;
REVOKE ALL ON FUNCTION theodb.graph_build(text,text,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb.graph_refold(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb.graph_expand(text,bigint[],int) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb.graph_expand_card(text,bigint[],int) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb.graph_expand_multi(text,int[],bigint[],int) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb.graph_expand_multi_card(text,int[],bigint[],int) FROM PUBLIC;
CREATE OR REPLACE FUNCTION theodb.graph_ppr(edge_rel text, seeds bigint[], damping float8 DEFAULT 0.5, iters int DEFAULT 20)
  RETURNS TABLE(node bigint, score float8)
  LANGUAGE sql VOLATILE AS $fn$ SELECT * FROM theodb_rs.graph_ppr($1,$2,$3,$4) $fn$;
REVOKE ALL ON FUNCTION theodb.graph_ppr(text,bigint[],float8,int) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph.rs:550
-- requires:
--   graph_build
--   graph_refold
--   graph_expand
--   graph_expand_card
--   graph_expand_multi
--   graph_expand_multi_card
--   graph_ppr


DO $$
DECLARE r record;
BEGIN
    FOR r IN SELECT p.oid::regprocedure AS sig FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
             WHERE n.nspname='theodb_rs' AND p.proname ~ '^graph_'
    LOOP EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC', r.sig); END LOOP;
END $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:11
CREATE SCHEMA IF NOT EXISTS theodb_rs; /* theodb_rs::api::theodb_rs */
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:133
-- theodb_rs::api::theodb_rs::_ai_if
CREATE OR REPLACE  FUNCTION theodb_rs."_ai_if"(
	"prompt" TEXT, /* Option < & str > */
	"model" TEXT /* Option < & str > */
) RETURNS bool /* bool */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_ai_if_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:261
-- theodb_rs::api::theodb_rs::_import_vectors
CREATE OR REPLACE  FUNCTION theodb_rs."_import_vectors"(
	"target_text" TEXT, /* & str */
	"export" jsonb, /* pgrx :: JsonB */
	"id_col" TEXT, /* & str */
	"embedding_col" TEXT, /* & str */
	"metadata_col" TEXT /* & str */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_import_vectors_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:771
-- requires:
--   _import_vectors
--   theodb_schema_bootstrap


CREATE OR REPLACE FUNCTION theodb.import_vectors(
    target        regclass,
    export        jsonb,
    id_col        text DEFAULT 'id',
    embedding_col text DEFAULT 'embedding',
    metadata_col  text DEFAULT 'metadata'
) RETURNS integer
LANGUAGE sql
AS $$ SELECT theodb_rs._import_vectors(target::text, export, id_col, embedding_col, metadata_col) $$;

COMMENT ON FUNCTION theodb.import_vectors(regclass, jsonb, text, text, text) IS
  'Import a Pinecone export (JSON array of {id,values,metadata}) into a TheoDB table (id, embedding vector, '
  'metadata jsonb). Native jsonb (serde); safe dynamic SQL (%I-quoted, regclass-validated, parameter-bound). '
  'Implemented in Rust (theodb_rs, M19). Fail-fast 22023 on a non-array export or a record missing id/values. '
  'For large/atomic-vs-chunked imports see theodb.import_vectors_chunked (PROCEDURE). Not granted to PUBLIC.';

REVOKE ALL ON FUNCTION theodb.import_vectors(regclass, jsonb, text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._import_vectors(text, jsonb, text, text, text) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:339
-- theodb_rs::api::theodb_rs::_ivfflat_knn
CREATE OR REPLACE  FUNCTION theodb_rs."_ivfflat_knn"(
	"src_table" TEXT, /* & str */
	"embed_col" TEXT, /* & str */
	"id_col" TEXT, /* & str */
	"metric" TEXT, /* & str */
	"queries" real[], /* Vec < f32 > */
	"qdim" INT, /* i32 */
	"k" INT, /* i32 */
	"lists" INT, /* i32 */
	"probes" INT, /* i32 */
	"seed" bigint /* i64 */
) RETURNS TABLE (
	"query_idx" INT,  /* i32 */
	"id" bigint,  /* i64 */
	"distance" double precision  /* f64 */
)
STRICT VOLATILE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_ivfflat_knn_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:18
-- theodb_rs::api::theodb_rs::_embed_text
CREATE OR REPLACE  FUNCTION theodb_rs."_embed_text"(
	"content" TEXT, /* Option < & str > */
	"model" TEXT /* Option < & str > */
) RETURNS TEXT /* String */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_embed_text_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:457
-- requires:
--   _embed_text
--   theodb_schema_bootstrap


CREATE OR REPLACE FUNCTION theodb.embed(content text, model text DEFAULT NULL)
RETURNS vector
LANGUAGE sql
AS $$ SELECT theodb_rs._embed_text(content, model)::vector $$;

COMMENT ON FUNCTION theodb.embed(text, text) IS
  'Generate an embedding for content via the configurable model endpoint (theodb.embedding_endpoint). '
  'Returns a pgvector value. Implemented in Rust (theodb_rs extension, M17). '
  'SECURITY: server-side outbound HTTP to the configured endpoint (http(s) only, no redirects); '
  'not granted to PUBLIC. theodb.embedding_api_key is a session GUC (visible to SHOW / captured by '
  'log_statement) — set it per-session out of band, not in logged DDL. '
  'CALL IS SYNCHRONOUS: one blocking HTTP round-trip per row.';

REVOKE ALL ON FUNCTION theodb.embed(text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._embed_text(text, text) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:38
-- theodb_rs::api::theodb_rs::_chunk_text
CREATE OR REPLACE  FUNCTION theodb_rs."_chunk_text"(
	"content" TEXT, /* Option < & str > */
	"strategy" TEXT, /* & str */
	"chunk_size" INT, /* i32 */
	"overlap" INT /* i32 */
) RETURNS TEXT[] /* Vec < String > */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_chunk_text_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:512
-- requires:
--   _chunk_text
--   theodb_schema_bootstrap


CREATE OR REPLACE FUNCTION theodb.chunk(content text, strategy text DEFAULT 'recursive',
                             chunk_size int DEFAULT 512, overlap int DEFAULT 64)
RETURNS text[] LANGUAGE sql IMMUTABLE
AS $$ SELECT theodb_rs._chunk_text(content, strategy, chunk_size, overlap) $$;

COMMENT ON FUNCTION theodb.chunk(text, text, int, int) IS
  'Declarative text chunking (M66): split content into overlapping chunks by strategy '
  '(fixed | sentence | recursive). Char-based, Unicode-safe (never splits a multibyte grapheme). '
  'Empty content -> zero chunks; overlap must be < chunk_size (else typed error). Implemented in Rust (theodb_rs).';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:145
-- theodb_rs::api::theodb_rs::_ai_rank
CREATE OR REPLACE  FUNCTION theodb_rs."_ai_rank"(
	"prompt" TEXT, /* Option < & str > */
	"model" TEXT /* Option < & str > */
) RETURNS real /* f32 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_ai_rank_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:96
-- theodb_rs::api::theodb_rs::_explain_scan
CREATE OR REPLACE  FUNCTION theodb_rs."_explain_scan"(
	"relid" oid, /* pg_sys :: Oid */
	"index_name" TEXT, /* & str */
	"tbl" TEXT, /* & str */
	"vec_col" TEXT, /* & str */
	"query" TEXT, /* & str */
	"ef" INT, /* i32 */
	"k" INT /* i32 */
) RETURNS TABLE (
	"index_name" TEXT,  /* String */
	"ef_effective" INT,  /* i32 */
	"pages_read" bigint,  /* i64 */
	"candidates_seen" bigint,  /* i64 */
	"latency_us" bigint,  /* i64 */
	"results" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_explain_scan_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:580
-- requires:
--   _explain_scan
--   theodb_schema_bootstrap


CREATE OR REPLACE FUNCTION theodb.explain_scan(index_table regclass, vector_col text, query text,
                                    ef int DEFAULT 100, k int DEFAULT 10)
RETURNS TABLE(index_name text, ef_effective int, pages_read bigint, candidates_seen bigint, latency_us bigint, results bigint)
LANGUAGE sql
AS $$ SELECT index_name, ef_effective, pages_read, candidates_seen, latency_us, results
      FROM theodb_rs._explain_scan(
        index_table::oid,
        COALESCE((SELECT ci.relname FROM pg_index i JOIN pg_class ci ON ci.oid = i.indexrelid
                  JOIN pg_am a ON a.oid = ci.relam
                  WHERE i.indrelid = index_table AND a.amname = 'theodb_hnsw' LIMIT 1),
                 '(no theodb_hnsw index on this table)'),
        index_table::text, vector_col, query, ef, k) $$;

COMMENT ON FUNCTION theodb.explain_scan(regclass, text, text, int, int) IS
  'EXPLAIN the vector scan (M68): index, effective ef, pages_read, candidates_seen (the beam pool navigated), '
  'latency, results. A diagnostic function (PG18 has no amexplain hook — the Qdrant/Milvus pattern). See '
  'docs/ops/vector-scan-diagnostics.md. Not granted to PUBLIC.';

REVOKE ALL ON FUNCTION theodb.explain_scan(regclass, text, text, int, int) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._explain_scan(oid, text, text, text, text, int, int) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:290
-- theodb_rs::api::theodb_rs::_vec_cosine
CREATE OR REPLACE  FUNCTION theodb_rs."_vec_cosine"(
	"a" real[], /* Vec < f32 > */
	"b" real[] /* Vec < f32 > */
) RETURNS double precision /* f64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_vec_cosine_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:169
-- theodb_rs::api::theodb_rs::_ai_rerank
CREATE OR REPLACE  FUNCTION theodb_rs."_ai_rerank"(
	"query" TEXT, /* Option < & str > */
	"documents" TEXT[], /* :: std :: option :: Option < Vec < Option < String > > > */
	"model" TEXT, /* Option < & str > */
	"top_n" INT /* Option < i32 > */
) RETURNS TABLE (
	"idx" INT,  /* i32 */
	"score" real  /* f32 */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_ai_rerank_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:659
-- requires:
--   _ai_rerank
--   theodb_schema_bootstrap


CREATE OR REPLACE FUNCTION ai.rerank(query text, documents text[], model text DEFAULT NULL, top_n int DEFAULT NULL)
RETURNS TABLE(idx int, score real) LANGUAGE sql VOLATILE
AS $$ SELECT idx, score FROM theodb_rs._ai_rerank(query, documents, model, top_n) $$;

COMMENT ON FUNCTION ai.rerank(text, text[], text, int) IS
  'Cross-encoder rerank (M65): scores each document against the query via theodb.rerank_endpoint '
  '(http(s)-only, no redirects) and returns TABLE(idx, score) sorted by relevance DESC — idx is 0-based '
  'into the documents array (join it back to the source rows). top_n NULL = all. Implemented in Rust '
  '(theodb_rs), reusing the ai.embed HTTP client. Not granted to PUBLIC. theodb.rerank_api_key is a session GUC.';

REVOKE ALL ON FUNCTION ai.rerank(text, text[], text, int) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._ai_rerank(text, text[], text, int) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:139
-- theodb_rs::api::theodb_rs::_ai_sentiment
CREATE OR REPLACE  FUNCTION theodb_rs."_ai_sentiment"(
	"content" TEXT, /* Option < & str > */
	"model" TEXT /* Option < & str > */
) RETURNS TEXT /* String */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_ai_sentiment_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:409
-- theodb_rs::api::theodb_rs::_sbq_bytes_per_vector
CREATE OR REPLACE  FUNCTION theodb_rs."_sbq_bytes_per_vector"(
	"dim" INT, /* i32 */
	"bits" INT /* i32 */
) RETURNS bigint /* i64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_sbq_bytes_per_vector_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:71
-- theodb_rs::api::theodb_rs::_scan_stats
CREATE OR REPLACE  FUNCTION theodb_rs."_scan_stats"(
	"relid" oid, /* pg_sys :: Oid */
	"tbl" TEXT, /* & str */
	"vec_col" TEXT, /* & str */
	"query" TEXT, /* & str */
	"ef" INT, /* i32 */
	"k" INT /* i32 */
) RETURNS TABLE (
	"pages_read" bigint,  /* i64 */
	"candidates_seen" bigint,  /* i64 */
	"latency_us" bigint,  /* i64 */
	"results" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_scan_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:554
-- requires:
--   _scan_stats
--   theodb_schema_bootstrap


CREATE OR REPLACE FUNCTION theodb.scan_stats(index_table regclass, vector_col text, query text,
                                  ef int DEFAULT 100, k int DEFAULT 10)
RETURNS TABLE(pages_read bigint, candidates_seen bigint, latency_us bigint, results bigint) LANGUAGE sql
AS $$ SELECT pages_read, candidates_seen, latency_us, results FROM theodb_rs._scan_stats(index_table::oid, index_table::text, vector_col, query, ef, k) $$;

CREATE OR REPLACE FUNCTION theodb.index_scan_stats(rel regclass)
RETURNS TABLE(n_scans bigint, avg_pages_read numeric, avg_candidates numeric, avg_latency_us numeric, last_ef int, last_updated timestamptz)
LANGUAGE sql STABLE
AS $$ SELECT n_scans, round(sum_pages_read::numeric/GREATEST(n_scans,1),1), round(sum_candidates::numeric/GREATEST(n_scans,1),1), round(sum_latency_us::numeric/GREATEST(n_scans,1),1), last_ef, last_updated
      FROM theodb._index_scan_stats WHERE relid = rel::oid $$;

COMMENT ON FUNCTION theodb.scan_stats(regclass, text, text, int, int) IS
  'Measure one theodb_hnsw scan at ef: returns the REAL observed pages_read + candidates_seen + latency (M67/M68 '
  'collector) and persists it. Lets the operator audit amcostestimate against reality. Not PUBLIC.';

REVOKE ALL ON FUNCTION theodb.scan_stats(regclass, text, text, int, int) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._scan_stats(oid, text, text, text, int, int) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:152
-- theodb_rs::api::theodb_rs::_ai_generate_batch
CREATE OR REPLACE  FUNCTION theodb_rs."_ai_generate_batch"(
	"prompts" TEXT[], /* :: std :: option :: Option < Vec < Option < String > > > */
	"model" TEXT /* Option < & str > */
) RETURNS TEXT[] /* Vec < Option < String > > */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_ai_generate_batch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:302
-- theodb_rs::api::theodb_rs::_hnsw_knn
CREATE OR REPLACE  FUNCTION theodb_rs."_hnsw_knn"(
	"src_table" TEXT, /* & str */
	"embed_col" TEXT, /* & str */
	"id_col" TEXT, /* & str */
	"metric" TEXT, /* & str */
	"queries" real[], /* Vec < f32 > */
	"qdim" INT, /* i32 */
	"k" INT, /* i32 */
	"m" INT, /* i32 */
	"ef_construction" INT, /* i32 */
	"ef_search" INT, /* i32 */
	"seed" bigint /* i64 */
) RETURNS TABLE (
	"query_idx" INT,  /* i32 */
	"id" bigint,  /* i64 */
	"distance" double precision  /* f64 */
)
STRICT VOLATILE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_hnsw_knn_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:846
-- requires:
--   _hnsw_knn
--   _ivfflat_knn
--   theodb_schema_bootstrap


CREATE OR REPLACE FUNCTION theodb.hnsw_knn(
    src_table       regclass,
    embed_col       text,
    queries         vector[],
    k               int    DEFAULT 10,
    m               int    DEFAULT 16,
    ef_construction int    DEFAULT 64,
    ef_search       int    DEFAULT 40,
    metric          text   DEFAULT 'l2',
    id_col          text   DEFAULT 'id',
    seed            bigint DEFAULT 42
) RETURNS TABLE(query_idx int, id bigint, distance float8)
LANGUAGE sql VOLATILE
AS $$
  SELECT query_idx, id, distance FROM theodb_rs._hnsw_knn(
    src_table::text, embed_col, id_col, metric,
    (SELECT COALESCE(array_agg(x ORDER BY qi, ci), ARRAY[]::real[])
       FROM unnest(queries) WITH ORDINALITY AS u(qv, qi),
            unnest(qv::real[]) WITH ORDINALITY AS e(x, ci)),
    COALESCE(array_length((queries[1])::real[], 1), 1),
    k, m, ef_construction, ef_search, seed)
$$;

CREATE OR REPLACE FUNCTION theodb.ivfflat_knn(
    src_table       regclass,
    embed_col       text,
    queries         vector[],
    k               int    DEFAULT 10,
    lists           int    DEFAULT 100,
    probes          int    DEFAULT 1,
    metric          text   DEFAULT 'l2',
    id_col          text   DEFAULT 'id',
    seed            bigint DEFAULT 42
) RETURNS TABLE(query_idx int, id bigint, distance float8)
LANGUAGE sql VOLATILE
AS $$
  SELECT query_idx, id, distance FROM theodb_rs._ivfflat_knn(
    src_table::text, embed_col, id_col, metric,
    (SELECT COALESCE(array_agg(x ORDER BY qi, ci), ARRAY[]::real[])
       FROM unnest(queries) WITH ORDINALITY AS u(qv, qi),
            unnest(qv::real[]) WITH ORDINALITY AS e(x, ci)),
    COALESCE(array_length((queries[1])::real[], 1), 1),
    k, lists, probes, seed)
$$;

COMMENT ON FUNCTION theodb.hnsw_knn(regclass, text, vector[], int, int, int, int, text, text, bigint) IS
  'TheoDB own HNSW ANN search (M21): build a Hierarchical Navigable Small World graph over src_table.embed_col '
  'in Rust and answer a batch of top-k queries (<->/<#>/<=>). Recall@k is gated vs pgvector by '
  'benchmarks/bench_ann_index.py. Coexists with pgvector (reads vector::real[]; no competing index). '
  'Measurement-first SQL-callable form (ADR D1); not granted to PUBLIC.';
COMMENT ON FUNCTION theodb.ivfflat_knn(regclass, text, vector[], int, int, int, text, text, bigint) IS
  'TheoDB own IVFFlat ANN search (M21): k-means++ inverted lists over src_table.embed_col in Rust, scan the '
  'probes nearest lists. Recall@k gated vs pgvector. Coexists with pgvector. Not granted to PUBLIC.';

REVOKE ALL ON FUNCTION theodb.hnsw_knn(regclass, text, vector[], int, int, int, int, text, text, bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb.ivfflat_knn(regclass, text, vector[], int, int, int, text, text, bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._hnsw_knn(text, text, text, text, real[], int, int, int, int, int, bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._ivfflat_knn(text, text, text, text, real[], int, int, int, int, bigint) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:127
-- theodb_rs::api::theodb_rs::_ai_chat
CREATE OR REPLACE  FUNCTION theodb_rs."_ai_chat"(
	"prompt" TEXT, /* Option < & str > */
	"system" TEXT, /* Option < & str > */
	"model" TEXT /* Option < & str > */
) RETURNS TEXT /* String */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_ai_chat_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:612
-- requires:
--   _ai_chat
--   _ai_if
--   _ai_sentiment
--   _ai_rank
--   _ai_generate_batch
--   theodb_schema_bootstrap


CREATE OR REPLACE FUNCTION ai._chat(prompt text, system text DEFAULT NULL, model text DEFAULT NULL)
RETURNS text LANGUAGE sql VOLATILE
AS $$ SELECT theodb_rs._ai_chat(prompt, system, model) $$;

CREATE OR REPLACE FUNCTION ai."if"(prompt text, model text DEFAULT NULL)
RETURNS boolean LANGUAGE sql VOLATILE
AS $$ SELECT theodb_rs._ai_if(prompt, model) $$;

CREATE OR REPLACE FUNCTION ai.analyze_sentiment(content text, model text DEFAULT NULL)
RETURNS text LANGUAGE sql VOLATILE
AS $$ SELECT theodb_rs._ai_sentiment(content, model) $$;

CREATE OR REPLACE FUNCTION ai.rank(prompt text, model text DEFAULT NULL)
RETURNS real LANGUAGE sql VOLATILE
AS $$ SELECT theodb_rs._ai_rank(prompt, model) $$;

CREATE OR REPLACE FUNCTION ai.generate_batch(prompts text[], model text DEFAULT NULL)
RETURNS text[] LANGUAGE sql VOLATILE
AS $$ SELECT theodb_rs._ai_generate_batch(prompts, model) $$;

COMMENT ON FUNCTION ai._chat(text, text, text) IS
  'PRIVATE: one configurable chat-completions round-trip (theodb.llm_endpoint, http(s)-only, no redirects) '
  '+ parse of choices[0].message.content. Single HTTP source of truth for the public ai.* functions. '
  'Implemented in Rust (theodb_rs, M18). Not granted to PUBLIC. theodb.llm_api_key is a session GUC.';

REVOKE ALL ON FUNCTION ai._chat(text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION ai."if"(text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION ai.analyze_sentiment(text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION ai.rank(text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION ai.generate_batch(text[], text) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._ai_chat(text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._ai_if(text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._ai_sentiment(text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._ai_rank(text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._ai_generate_batch(text[], text) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/ai_op.rs:118
-- requires:
--   _ai_if_batch
--   _ai_if_costly
--   _ai_call_count
--   _ai_call_reset
--   theodb_ai_wrappers


CREATE OR REPLACE FUNCTION ai.if_batch(condition text, vals text[], model text DEFAULT NULL)
RETURNS boolean[] LANGUAGE sql VOLATILE
AS $$ SELECT theodb_rs._ai_if_batch(condition, vals, model) $$;

CREATE OR REPLACE FUNCTION ai.if_costly(condition text, val text, model text DEFAULT NULL)
RETURNS boolean LANGUAGE sql VOLATILE COST 100000
AS $$ SELECT theodb_rs._ai_if_costly(condition, val, model) $$;

CREATE OR REPLACE FUNCTION ai.call_count() RETURNS bigint LANGUAGE sql VOLATILE
AS $$ SELECT theodb_rs._ai_call_count() $$;

CREATE OR REPLACE FUNCTION ai.call_reset() RETURNS void LANGUAGE sql VOLATILE
AS $$ SELECT theodb_rs._ai_call_reset() $$;

COMMENT ON FUNCTION ai.if_batch(text, text[], text) IS
  'SET-oriented AI.IF: N values -> N booleans in ONE inference round-trip (batched, yes/no-shaped). '
  'Comparable to the per-row ai.if on "{condition}: {value}". NULL value -> NULL bool. SECURITY: values become '
  'LLM prompt input (prompt-injection surface, blast radius = the row own boolean); NEVER GRANT to an isolated '
  'role. Implemented in Rust (theodb_rs, M102).';
COMMENT ON FUNCTION ai.if_costly(text, text, text) IS
  'Per-row AI.IF declared with a high COST so the planner evaluates cheaper relational quals first '
  '(dependency-safe filter push-down). Observe the row reduction via ai.call_count(). SECURITY: values become '
  'LLM prompt input; NEVER GRANT to an isolated role. theodb_rs, M102.';

REVOKE ALL ON FUNCTION ai.if_batch(text, text[], text) FROM PUBLIC;
REVOKE ALL ON FUNCTION ai.if_costly(text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._ai_if_batch(text, text[], text) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._ai_if_costly(text, text, text) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:251
-- theodb_rs::api::theodb_rs::_hybrid_search_json
CREATE OR REPLACE  FUNCTION theodb_rs."_hybrid_search_json"(
	"config" jsonb /* pgrx :: JsonB */
) RETURNS TABLE (
	"id" TEXT,  /* String */
	"score" real  /* f32 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_hybrid_search_json_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:284
-- theodb_rs::api::theodb_rs::_vec_ip
CREATE OR REPLACE  FUNCTION theodb_rs."_vec_ip"(
	"a" real[], /* Vec < f32 > */
	"b" real[] /* Vec < f32 > */
) RETURNS double precision /* f64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_vec_ip_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:427
-- theodb_rs::api::theodb_rs::_pq_knn
CREATE OR REPLACE  FUNCTION theodb_rs."_pq_knn"(
	"src_table" TEXT, /* & str */
	"embed_col" TEXT, /* & str */
	"id_col" TEXT, /* & str */
	"metric" TEXT, /* & str */
	"queries" real[], /* Vec < f32 > */
	"qdim" INT, /* i32 */
	"k" INT, /* i32 */
	"m" INT, /* i32 */
	"lists" INT, /* i32 */
	"probes" INT, /* i32 */
	"over_fetch" INT, /* i32 */
	"seed" bigint /* i64 */
) RETURNS TABLE (
	"query_idx" INT,  /* i32 */
	"id" bigint,  /* i64 */
	"distance" double precision  /* f64 */
)
STRICT VOLATILE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_pq_knn_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:969
-- requires:
--   _pq_knn
--   theodb_schema_bootstrap


CREATE OR REPLACE FUNCTION theodb.pq_knn(
    src_table  regclass,
    embed_col  text,
    queries    vector[],
    k          int    DEFAULT 10,
    m          int    DEFAULT 8,
    lists      int    DEFAULT 100,
    probes     int    DEFAULT 1,
    over_fetch int    DEFAULT 4,
    metric     text   DEFAULT 'l2',
    id_col     text   DEFAULT 'id',
    seed       bigint DEFAULT 42
) RETURNS TABLE(query_idx int, id bigint, distance float8)
LANGUAGE sql VOLATILE
AS $$
  SELECT query_idx, id, distance FROM theodb_rs._pq_knn(
    src_table::text, embed_col, id_col, metric,
    (SELECT COALESCE(array_agg(x ORDER BY qi, ci), ARRAY[]::real[])
       FROM unnest(queries) WITH ORDINALITY AS u(qv, qi),
            unnest(qv::real[]) WITH ORDINALITY AS e(x, ci)),
    COALESCE(array_length((queries[1])::real[], 1), 1),
    k, m, lists, probes, over_fetch, seed)
$$;

COMMENT ON FUNCTION theodb.pq_knn(regclass, text, vector[], int, int, int, int, int, text, text, bigint) IS
  'TheoDB own Product Quantization ANN search (M39): per-subspace k-means codebooks (own Rust, permissive — '
  'NOT the AGPL RaBitQ/k_means), asymmetric distance (ADC) via per-query LUT, candidate-gen via the M21 IVFFlat '
  'carrier, ADC rank + full-precision f32 rerank. Benchmark-gated vs SBQ (D3); measurement-first SQL-callable; '
  'not granted to PUBLIC.';

REVOKE ALL ON FUNCTION theodb.pq_knn(regclass, text, vector[], int, int, int, int, int, text, text, bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._pq_knn(text, text, text, text, real[], int, int, int, int, int, int, bigint) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:380
-- theodb_rs::api::theodb_rs::_sbq_knn
CREATE OR REPLACE  FUNCTION theodb_rs."_sbq_knn"(
	"src_table" TEXT, /* & str */
	"embed_col" TEXT, /* & str */
	"id_col" TEXT, /* & str */
	"metric" TEXT, /* & str */
	"queries" real[], /* Vec < f32 > */
	"qdim" INT, /* i32 */
	"k" INT, /* i32 */
	"bits" INT, /* i32 */
	"lists" INT, /* i32 */
	"probes" INT, /* i32 */
	"over_fetch" INT, /* i32 */
	"seed" bigint /* i64 */
) RETURNS TABLE (
	"query_idx" INT,  /* i32 */
	"id" bigint,  /* i64 */
	"distance" double precision  /* f64 */
)
STRICT VOLATILE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_sbq_knn_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:917
-- requires:
--   _sbq_knn
--   _sbq_bytes_per_vector
--   theodb_schema_bootstrap


CREATE OR REPLACE FUNCTION theodb.sbq_knn(
    src_table  regclass,
    embed_col  text,
    queries    vector[],
    k          int    DEFAULT 10,
    bits       int    DEFAULT 1,
    lists      int    DEFAULT 100,
    probes     int    DEFAULT 1,
    over_fetch int    DEFAULT 4,
    metric     text   DEFAULT 'l2',
    id_col     text   DEFAULT 'id',
    seed       bigint DEFAULT 42
) RETURNS TABLE(query_idx int, id bigint, distance float8)
LANGUAGE sql VOLATILE
AS $$
  SELECT query_idx, id, distance FROM theodb_rs._sbq_knn(
    src_table::text, embed_col, id_col, metric,
    (SELECT COALESCE(array_agg(x ORDER BY qi, ci), ARRAY[]::real[])
       FROM unnest(queries) WITH ORDINALITY AS u(qv, qi),
            unnest(qv::real[]) WITH ORDINALITY AS e(x, ci)),
    COALESCE(array_length((queries[1])::real[], 1), 1),
    k, bits, lists, probes, over_fetch, seed)
$$;

CREATE OR REPLACE FUNCTION theodb.sbq_bytes_per_vector(dim int, bits int DEFAULT 1)
RETURNS bigint LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
AS $$ SELECT theodb_rs._sbq_bytes_per_vector(dim, bits) $$;

COMMENT ON FUNCTION theodb.sbq_knn(regclass, text, vector[], int, int, int, int, int, text, text, bigint) IS
  'TheoDB own SBQ quantized ANN search (M22): per-dimension mean-threshold scalar bit quantization (own Rust, '
  'permissive — NOT the AGPL RaBitQ), candidate-gen via the M21 IVFFlat carrier, Hamming rank + full-precision '
  'f32 rerank. recall@k gated vs pgvectorscale; memory = bytes/vector (theodb.sbq_bytes_per_vector). Coexists '
  'with pgvectorscale/pgvector. Measurement-first SQL-callable (planner AM = M22b); not granted to PUBLIC.';
COMMENT ON FUNCTION theodb.sbq_bytes_per_vector(int, int) IS
  'Own SBQ storage footprint bytes/vector = ceil(dim*bits/64)*8 (parity with pgvectorscale at matched bits; '
  '~Nx reduction vs f32 4*dim). The memory metric for the M22 gate. Implemented in Rust (theodb_rs, M22).';

REVOKE ALL ON FUNCTION theodb.sbq_knn(regclass, text, vector[], int, int, int, int, int, text, text, bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._sbq_knn(text, text, text, text, real[], int, int, int, int, int, int, bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb.sbq_bytes_per_vector(int, int) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._sbq_bytes_per_vector(int, int) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:27
-- theodb_rs::api::theodb_rs::_embed_batch_text
CREATE OR REPLACE  FUNCTION theodb_rs."_embed_batch_text"(
	"content" TEXT[], /* Vec < Option < String > > */
	"model" TEXT /* Option < & str > */
) RETURNS TEXT[] /* Vec < String > */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_embed_batch_text_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:486
-- requires:
--   _embed_batch_text
--   theodb_schema_bootstrap


CREATE OR REPLACE FUNCTION theodb.embed_batch(content text[], model text DEFAULT NULL)
RETURNS vector[]
LANGUAGE sql
AS $$
  SELECT COALESCE(array_agg(t::vector ORDER BY ord), ARRAY[]::vector[])
  FROM unnest(theodb_rs._embed_batch_text(content, model)) WITH ORDINALITY AS u(t, ord)
$$;

COMMENT ON FUNCTION theodb.embed_batch(text[], text) IS
  'Generate embeddings for an array of inputs in ONE HTTP round-trip (collapses the per-row embed N+1). '
  'Returns vector[] aligned to the input order. Implemented in Rust (theodb_rs, audit-remediation). '
  'Mirrors ai.generate_batch N-in/N-out: a size mismatch is a typed error, NULL elements are rejected, '
  'an empty array returns an empty vector[] with no HTTP call. Not granted to PUBLIC.';

REVOKE ALL ON FUNCTION theodb.embed_batch(text[], text) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._embed_batch_text(text[], text) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:55
-- theodb_rs::api::theodb_rs::_recommend_ef
CREATE OR REPLACE  FUNCTION theodb_rs."_recommend_ef"(
	"tbl" TEXT, /* & str */
	"vec_col" TEXT, /* & str */
	"samples" TEXT[], /* Vec < Option < String > > */
	"recall_target" double precision, /* f64 */
	"k" INT /* i32 */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_recommend_ef_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:531
-- requires:
--   _recommend_ef
--   theodb_schema_bootstrap


CREATE OR REPLACE FUNCTION theodb.recommend_ef(index_table regclass, vector_col text, sample_queries text[],
                                    recall_target float DEFAULT 0.95, k int DEFAULT 10)
RETURNS int LANGUAGE sql
AS $$ SELECT theodb_rs._recommend_ef(index_table::text, vector_col, sample_queries, recall_target, k) $$;

COMMENT ON FUNCTION theodb.recommend_ef(regclass, text, text[], float, int) IS
  'Recommend the minimum theodb_hnsw.ef_search that reaches recall_target (default 0.95) on a sample of query '
  'vectors, measured against an exact seqscan ground truth (bisection over the monotone recall(ef) curve, M67). '
  'Read-only; the operator applies the result with SET theodb_hnsw.ef_search. Not granted to PUBLIC.';

REVOKE ALL ON FUNCTION theodb.recommend_ef(regclass, text, text[], float, int) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._recommend_ef(text, text, text[], float, int) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:211
-- theodb_rs::api::theodb_rs::_hybrid_search_rrf
CREATE OR REPLACE  FUNCTION theodb_rs."_hybrid_search_rrf"(
	"tbl_text" TEXT, /* & str */
	"id_col" TEXT, /* & str */
	"content_tsv_col" TEXT, /* & str */
	"vector_col" TEXT, /* & str */
	"query_text" TEXT, /* Option < & str > */
	"query_vector_text" TEXT, /* Option < & str > */
	"k" INT, /* i32 */
	"per_leg_limit" INT, /* i32 */
	"result_limit" INT, /* i32 */
	"language" TEXT, /* & str */
	"filter_sql" TEXT, /* Option < & str > */
	"lexical_engine" TEXT, /* & str */
	"content_text_col" TEXT /* Option < & str > */
) RETURNS TABLE (
	"id" TEXT,  /* String */
	"score" real  /* f32 */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_hybrid_search_rrf_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:709
-- requires:
--   _hybrid_search_rrf
--   _hybrid_search_json
--   theodb_schema_bootstrap


CREATE OR REPLACE FUNCTION ai.hybrid_search_rrf(
    tbl              regclass,
    id_col           text,
    content_tsv_col  text,
    vector_col       text,
    query_text       text    DEFAULT NULL,
    query_vector     vector  DEFAULT NULL,
    k                int     DEFAULT 60,
    per_leg_limit    int     DEFAULT 20,
    result_limit     int     DEFAULT 5,
    language         text    DEFAULT 'english',
    filter_sql       text    DEFAULT NULL,
    lexical_engine   text    DEFAULT 'ts_rank_cd',
    content_text_col text    DEFAULT NULL
)
RETURNS TABLE(id text, score real)
LANGUAGE sql STABLE
AS $$
  SELECT id, score FROM theodb_rs._hybrid_search_rrf(
    tbl::text, id_col, content_tsv_col, vector_col, query_text, query_vector::text,
    k, per_leg_limit, result_limit, language, filter_sql, lexical_engine, content_text_col)
$$;

CREATE OR REPLACE FUNCTION ai.hybrid_search(config jsonb)
RETURNS TABLE(id text, score real)
LANGUAGE sql STABLE
AS $$ SELECT id, score FROM theodb_rs._hybrid_search_json(config) $$;

COMMENT ON FUNCTION ai.hybrid_search_rrf(regclass, text, text, text, text, vector, int, int, int, text, text, text, text) IS
  'Hybrid search: fuse a PostgreSQL FTS leg (ts_rank_cd over a tsvector column) and a pgvector leg (<=>) via '
  'Reciprocal Rank Fusion (score = sum 1/(k+rank), k default 60 — Cormack et al. 2009). Empty legs handled by '
  'FULL OUTER JOIN + COALESCE. query_text feeds FTS and, when query_vector is NULL, is embedded via '
  'theodb.embed. Implemented in Rust (theodb_rs, M19) — orchestrates ONE fusion SQL via SPI (one fusion '
  'source of truth). IDENTIFIER args are %I-quoted and VALUE args are execution binds — both injection-safe. '
  'language parametrizes plainto_tsquery (default english). WARNING: filter_sql is RAW caller-privilege SQL '
  '(SECURITY INVOKER, read-only) inlined as a bare boolean predicate — NOT %I-quoted, NOT parametrized; its '
  'safety is syntactic confinement (rejects '';'' and SQL comments), NOT injection-proofing. NEVER build it '
  'from untrusted input, NEVER wrap this function in SECURITY DEFINER, NEVER GRANT to a role you intend to '
  'isolate. M53: lexical_engine (''ts_rank_cd'' default | ''bm25'') opts the lexical leg into pg_textsearch '
  'BM25 — bm25 requires content_text_col (the TEXT column indexed USING bm25) and the pg_textsearch extension '
  '(else 0A000); language is inert under bm25 (analyzer fixed at index build). Not granted to PUBLIC.';

COMMENT ON FUNCTION ai.hybrid_search(jsonb) IS
  'Literal spec-06 JSON surface over ai.hybrid_search_rrf (one fusion definition). Implemented in Rust '
  '(theodb_rs, M19). Fail-fast 22023 on missing required keys (table, id_col, content_tsv_col, vector_col). '
  'Not granted to PUBLIC.';

REVOKE ALL ON FUNCTION ai.hybrid_search_rrf(regclass, text, text, text, text, vector, int, int, int, text, text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION ai.hybrid_search(jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._hybrid_search_rrf(text, text, text, text, text, text, int, int, int, text, text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._hybrid_search_json(jsonb) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:276
-- theodb_rs::api::theodb_rs::_vec_l2
CREATE OR REPLACE  FUNCTION theodb_rs."_vec_l2"(
	"a" real[], /* Vec < f32 > */
	"b" real[] /* Vec < f32 > */
) RETURNS double precision /* f64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_vec_l2_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:804
-- requires:
--   _vec_l2
--   _vec_ip
--   _vec_cosine
--   theodb_schema_bootstrap


CREATE OR REPLACE FUNCTION theodb.l2_distance(a vector, b vector) RETURNS float8
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
AS $$ SELECT theodb_rs._vec_l2(a::real[], b::real[]) $$;

CREATE OR REPLACE FUNCTION theodb.inner_product(a vector, b vector) RETURNS float8
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
AS $$ SELECT theodb_rs._vec_ip(a::real[], b::real[]) $$;

CREATE OR REPLACE FUNCTION theodb.cosine_distance(a vector, b vector) RETURNS float8
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
AS $$ SELECT theodb_rs._vec_cosine(a::real[], b::real[]) $$;

COMMENT ON FUNCTION theodb.l2_distance(vector, vector) IS
  'TheoDB own L2 distance (<->) over pgvector values, at f32 numeric parity with pgvector.l2_distance. '
  'Implemented in Rust (theodb_rs, M20). Coexists with pgvector (reads vector::real[]; no competing type).';
COMMENT ON FUNCTION theodb.inner_product(vector, vector) IS
  'TheoDB own inner product over pgvector values, at f32 parity with pgvector.inner_product. The <#> distance '
  'is -theodb.inner_product. Implemented in Rust (theodb_rs, M20).';
COMMENT ON FUNCTION theodb.cosine_distance(vector, vector) IS
  'TheoDB own cosine distance (<=>) over pgvector values, at f32 parity with pgvector.cosine_distance. '
  'Implemented in Rust (theodb_rs, M20).';

REVOKE ALL ON FUNCTION theodb.l2_distance(vector, vector) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb.inner_product(vector, vector) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb.cosine_distance(vector, vector) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._vec_l2(real[], real[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._vec_ip(real[], real[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._vec_cosine(real[], real[]) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:198
-- theodb_rs::api::theodb_rs::_nl_to_sql
CREATE OR REPLACE  FUNCTION theodb_rs."_nl_to_sql"(
	"question" TEXT, /* Option < & str > */
	"allowed_relations" TEXT[], /* Vec < Option < String > > */
	"model" TEXT /* Option < & str > */
) RETURNS TEXT /* String */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_nl_to_sql_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:682
-- requires:
--   _nl_to_sql
--   theodb_schema_bootstrap


CREATE OR REPLACE FUNCTION ai.nl_to_sql(question text, allowed_relations text[], model text DEFAULT NULL)
RETURNS text LANGUAGE sql VOLATILE
AS $$ SELECT theodb_rs._nl_to_sql(question, allowed_relations, model) $$;

COMMENT ON FUNCTION ai.nl_to_sql(text, text[], text) IS
  'Translate a natural-language question into ONE validated read-only SELECT over allowed_relations (via the '
  'configurable model). Defense: L2 static validation (single statement, SELECT/WITH-only, banned-function '
  'denylist) + L4 parser-grade relation allowlist (EXPLAIN enumerates every planned relation). Fail-fast '
  '22023. Does NOT execute. Implemented in Rust (theodb_rs, M19). Not granted to PUBLIC.';

REVOKE ALL ON FUNCTION ai.nl_to_sql(text, text[], text) FROM PUBLIC;
REVOKE ALL ON FUNCTION theodb_rs._nl_to_sql(text, text[], text) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph_pgq.rs:44
CREATE SCHEMA IF NOT EXISTS theodb_rs; /* theodb_rs::graph_pgq::theodb_rs */
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph_pgq.rs:53
-- theodb_rs::graph_pgq::theodb_rs::_pgq_match
CREATE OR REPLACE  FUNCTION theodb_rs."_pgq_match"(
	"edge_rel" TEXT, /* & str */
	"source_ids" bigint[], /* Vec < Option < i64 > > */
	"pattern" TEXT, /* & str */
	"default_max" INT /* i32 */
) RETURNS SETOF bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_pgq_match_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/graph_pgq.rs:106
-- requires:
--   _pgq_match
--   theodb_graph_wrappers


CREATE OR REPLACE FUNCTION theodb.pgq_match(edge_rel text, source_ids bigint[], pattern text DEFAULT '-[e*1..2]-', default_max int DEFAULT 3)
  RETURNS SETOF bigint LANGUAGE sql VOLATILE AS $fn$ SELECT theodb_rs._pgq_match($1,$2,$3,$4) $fn$;
REVOKE ALL ON FUNCTION theodb.pgq_match(text,bigint[],text,int) FROM PUBLIC;
/* </end connected objects> */



-- ------------------------------------------------------------------------------------------------
-- #219 — a superficie ADICIONADA depois que `default_version` congelou em 1.2.0.
--
-- As duas funcoes abaixo existem no `.so` desde o M168 mas NUNCA chegaram ao catalogo de uma
-- instalacao ja em 1.2.0: o pgrx nao gera script de upgrade (licao do M137), e sem cadeia
-- `1.2.0 -> 1.3.0` o `ALTER EXTENSION theodb_rs UPDATE` responde `ALTER EXTENSION` e nao carrega
-- nada. A falha e silenciosa ate alguem chamar a funcao e receber `does not exist`.
--
-- QUAIS SAO, medido e nao presumido: `scripts/sql-surface.sh a915f5f` (o commit que congelou o
-- 1.2.0) contra `HEAD` devolve exatamente estas duas, e nenhuma outra.
--
-- A FORMA e a que o pgrx emite para `#[pg_extern] fn name() -> i64`, confirmada em DUAS fontes
-- independentes para uma assinatura identica (`theodb_df_probe`): o proprio script 1.1.0->1.2.0 e o
-- `theodb_rs--1.2.0.sql` instalado dentro da imagem publicada.
-- ------------------------------------------------------------------------------------------------

-- theodb_rs::am::columnar::theodb_columnar_chunks_skipped
CREATE OR REPLACE  FUNCTION "theodb_columnar_chunks_skipped"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_columnar_chunks_skipped_wrapper';

-- theodb_rs::am::columnar::theodb_columnar_chunks_scanned
CREATE OR REPLACE  FUNCTION "theodb_columnar_chunks_scanned"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'theodb_columnar_chunks_scanned_wrapper';
